Repository oshanQQ/naka-chan, pull requests merged in 2021-10, with the labels that each got.

#4 :whale: add docker-compose
  docker-compose.yml
  docker/naka-chan-develop/Dockerfile
  docker/naka-chan/Dockerfile
Labels: docker

#5 試しにherokuにデプロイしてみる
  .github/workflows/deploy.yml
Labels: ci/cd

#8 プロジェクトをバイナリから実行するようにした
  Procfile
Labels: ci/cd

#11 helpコマンドとnakachanコマンドを実装してみた
  Cargo.lock
  Cargo.toml
  serenity.md
  songbird.md
  src/commands/mod.rs
  src/commands/nakachan.rs
  src/main.rs
Labels: feature

#13 正常終了しないようにループ処理を加えた
  Cargo.lock
  Cargo.toml
  src/commands/mod.rs
  src/commands/nakachan.rs
  src/main.rs
Labels: feature

#14 GitHub Actionsをもう一度走らせる
  README.md
Labels: ci/cd
